# Site settings
title_left    : "Gà"
title_right   : "code" # default: ""
description   : "Chào bạn, Tôi là Gàcode đây. Tôi ở đây vì một lý do duy nhất đó là chém gió về Web development, Ruby on Rails và cuộc sống. Tôi thích học những kiến thức về IT, à... cả business và finance nữa, haha."
keywords      : "Web development, Ruby on Rails, life, code, blog"
url           : https://gaacode.github.io/blog # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-136816195-1
twitter_username  : ""
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "vuongphan139"
postshare_enabled : true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Gàcode"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : articles
    title: Articles

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
